#pragma once

class PARAM_CPPROJ_CLASS_NAME
{
public:
    PARAM_CPPROJ_CLASS_NAME();
    ~PARAM_CPPROJ_CLASS_NAME();

private:
    PARAM_CPPROJ_CLASS_NAME(const PARAM_CPPROJ_CLASS_NAME&) = delete;
    PARAM_CPPROJ_CLASS_NAME operator=(const PARAM_CPPROJ_CLASS_NAME&) = delete;
};